module.exports = {
    parser: 'babel-eslint',
    extends: ['airbnb-base'],
    parserOptions: {
        ecmaVersion: 11,
    },
    plugins: ['html', 'simple-import-sort', 'babel'],
    rules: {
        'babel/no-unused-expressions': 'error',
        'class-methods-use-this': 'off',
        'dot-notation': 'off',
        'eol-last': ['error', 'always'],
        'import/extensions': 'off',
        'import/order': 'off',
        'max-len': ['error', { code: 120 }],
        'no-await-in-loop': 'off',
        'no-bitwise': 'off',
        'no-continue': 'off',
        'no-nested-ternary': 'off',
        'no-param-reassign': 'off',
        'no-plusplus': 'off',
        'no-restricted-globals': 'off',
        'no-restricted-globals': 'off',
        'no-restricted-syntax': 'off',
        'no-return-assign': 'off',
        'no-shadow': 'off',
        'no-undef': 'off',
        'no-underscore-dangle': 'off',
        'no-unused-expressions': 'off',
        'no-use-before-define': 'off',
        'object-curly-newline': 'off',
        'operator-linebreak': ['error', 'before'],
        'prefer-const': 'warn',
        'require-await': 'error',
        'require-yield': 'error',
        'simple-import-sort/sort': 'error',
        'sort-imports': 'off',
        indent: ['error', 4, { SwitchCase: 1, ignoredNodes: ['TemplateLiteral *'] }],
        quotes: ['error', 'single', { allowTemplateLiterals: true }],
        semi: ['error', 'always'],
    },
};
