module.exports = {
    "extends": [
        "airbnb",
        "airbnb/hooks"
    ],
    "rules": {
        "consistent-return": "off",
        "dot-notation": "off",
        "guard-for-in": "off",
        "indent": ["error", 4],
        "no-case-declarations": "off",
        "no-nested-ternary": "off",
        "import/first": "off",
        "import/no-extraneous-dependencies": "off",
        "import/no-unused-modules": ["warn", {"unusedExports": true}],
        "no-await-in-loop": "off",
        "no-bitwise": ["error", { "allow": ["&"] }],
        "no-console": "warn",
        "no-continue": "off",
        "no-unused-vars": ["warn", { "varsIgnorePattern": "css" }],
        "no-return-assign": "warn",
        "no-param-reassign": "off",
        "no-prototype-builtins": "warn",
        "no-restricted-syntax": "off",
        "no-shadow": "off",
        "max-len": ["error", { "code": 120 }],
        "global-require": "off",
        "object-curly-newline": "off",
        "operator-linebreak": "off",
        "camelcase": "off",
        "no-underscore-dangle": "off",
        "no-use-before-define": "off",
        "react/jsx-indent": ["error", 4],
        "react/jsx-indent-props": ["error", 4],
        "jsx-a11y/click-events-have-key-events": "off",
        "jsx-a11y/media-has-caption": "off",
        "jsx-a11y/no-static-element-interactions": "off",
        "react/jsx-filename-extension": "off",
        "react/prop-types": "off",
        "react/sort-comp": "off",
        "react/no-multi-comp": "off",
        "react/no-unused-state": "off",
        "react/display-name": "off",
        "react/jsx-closing-tag-location": "off",
        "react/jsx-wrap-multilines": "off",
    }
}